"""
AI Natural Language Report Generator — LLM-powered executive + technical reports.
Makes findings readable for both executives and technical teams.
"""
import json
import os
from pathlib import Path
from typing import Dict, List, Optional, Any
from datetime import datetime
from dataclasses import dataclass, field

from itzraven.core.logger import get_logger

logger = get_logger()

_REPORT_DIR = Path.home() / ".itzraven" / "reports"
_REPORT_DIR.mkdir(parents=True, exist_ok=True)


@dataclass
class AIReport:
    target: str
    scan_date: str
    executive_summary: str
    technical_summary: str
    risk_score: str
    risk_level: str
    critical_findings: List[Dict]
    high_findings: List[Dict]
    medium_findings: List[Dict]
    low_findings: List[Dict]
    attack_paths: List[str]
    recommendations: List[str]
    raw_findings: List[Dict] = field(default_factory=list)
    scan_duration: str = ""
    total_findings: int = 0

    def to_markdown(self) -> str:
        lines = [f"# Security Assessment Report: {self.target}", ""]
        lines.append(f"**Scan Date:** {self.scan_date}")
        lines.append(f"**Duration:** {self.scan_duration}")
        lines.append(f"**Risk Score:** {self.risk_score}/10 ({self.risk_level})")
        lines.append(f"**Total Findings:** {self.total_findings}")
        lines.append("")

        lines.append("## Executive Summary")
        lines.append("")
        lines.append(self.executive_summary)
        lines.append("")

        lines.append("## Risk Assessment")
        lines.append("")
        lines.append(f"- **Critical:** {len(self.critical_findings)}")
        lines.append(f"- **High:** {len(self.high_findings)}")
        lines.append(f"- **Medium:** {len(self.medium_findings)}")
        lines.append(f"- **Low:** {len(self.low_findings)}")
        lines.append("")

        if self.attack_paths:
            lines.append("## Attack Paths")
            lines.append("")
            for ap in self.attack_paths:
                lines.append(f"- {ap}")
            lines.append("")

        lines.append("## Findings by Severity")
        lines.append("")
        for severity, findings_list in [
            ("Critical", self.critical_findings),
            ("High", self.high_findings),
            ("Medium", self.medium_findings),
            ("Low", self.low_findings),
        ]:
            if not findings_list:
                continue
            lines.append(f"### {severity}")
            lines.append("")
            for f in findings_list:
                lines.append(f"#### {f.get('title', 'Unknown')}")
                lines.append("")
                lines.append(f"**Category:** {f.get('category', 'N/A')}")
                lines.append(f"**CVSS:** {f.get('cvss_score', 'N/A')} | **CWE:** {f.get('cwe_id', 'N/A')}")
                if f.get("description"):
                    lines.append(f"**Description:** {f['description']}")
                if f.get("evidence"):
                    lines.append(f"**Evidence:** ```{f['evidence'][:500]}```")
                if f.get("proof_of_concept"):
                    lines.append(f"**PoC:** `{f['proof_of_concept'][:300]}`")
                if f.get("remediation"):
                    lines.append(f"**Remediation:** {f['remediation']}")
                lines.append("")

        if self.recommendations:
            lines.append("## Recommendations")
            lines.append("")
            for r in self.recommendations:
                lines.append(f"- {r}")
            lines.append("")

        lines.append("## Technical Summary")
        lines.append("")
        lines.append(self.technical_summary)
        lines.append("")
        lines.append("---")
        lines.append(f"*Generated by Itzraven AI Security Scanner on {self.scan_date}*")

        return "\n".join(lines)


class AIReportGenerator:
    def __init__(self):
        self._llm = None
        self._report_dir = _REPORT_DIR

    async def _get_llm(self):
        if self._llm is None:
            from itzraven.agents.llm_client import LLMClient
            self._llm = LLMClient()
        return self._llm

    async def generate_report(self, findings: List[Dict], target: str,
                               scan_duration: str = "") -> AIReport:
        """Generate AI-powered report from findings."""
        now = datetime.now().isoformat()
        llm = await self._get_llm()

        # Categorize
        by_severity = {"critical": [], "high": [], "medium": [], "low": [], "info": []}
        for f in findings:
            sev = f.get("severity", "info").lower()
            by_severity.setdefault(sev, []).append(f)

        # Generate executive summary via LLM
        findings_summary = "\n".join(
            f"- [{f.get('severity','info').upper()}] {f.get('title','')} ({f.get('category','')})"
            for f in findings[:20]
        )

        try:
            exec_prompt = f"""You are a security report writer. Generate an executive summary for a penetration test.

Target: {target}
Total Findings: {len(findings)}
Findings:
{findings_summary}

Write a concise executive summary (3-5 sentences) that:
1. States the overall security posture
2. Highlights the most critical risks
3. Gives a high-level recommendation

Also provide a risk score (0-10) and level (Critical/High/Medium/Low).

Respond in JSON:
{{
    "executive_summary": "...",
    "technical_summary": "...",
    "risk_score": 7.5,
    "risk_level": "High",
    "attack_paths": ["...", "..."],
    "recommendations": ["...", "..."]
}}"""

            response = await llm.generate(
                prompt=exec_prompt,
                system="You are a professional security report writer. Respond with valid JSON only.",
                max_tokens=1000,
                temperature=0.3,
                task="report_generation",
            )
            text = response.text.strip()
            if "```json" in text:
                text = text.split("```json")[1].split("```")[0].strip()
            elif "```" in text:
                text = text.split("```")[1].split("```")[0].strip()
            ai_content = json.loads(text)
        except Exception as e:
            logger.debug(f"LLM report generation failed, using template: {e}")
            ai_content = self._template_summary(findings, target)

        # Build attack paths from findings
        attack_paths = ai_content.get("attack_paths", [])
        if not attack_paths:
            attack_paths = self._generate_attack_paths(findings)

        report = AIReport(
            target=target,
            scan_date=now,
            executive_summary=ai_content.get("executive_summary", "No executive summary available."),
            technical_summary=ai_content.get("technical_summary", "No technical summary available."),
            risk_score=str(ai_content.get("risk_score", 5.0)),
            risk_level=ai_content.get("risk_level", "Medium"),
            critical_findings=by_severity.get("critical", []) + by_severity.get("critical", []),
            high_findings=by_severity.get("high", []) + by_severity.get("high", []),
            medium_findings=by_severity.get("medium", []) + by_severity.get("medium", []),
            low_findings=by_severity.get("low", []) + by_severity.get("low", []),
            attack_paths=attack_paths,
            recommendations=ai_content.get("recommendations", ["Review all findings and patch accordingly."]),
            raw_findings=findings,
            scan_duration=scan_duration,
            total_findings=len(findings),
        )
        return report

    def _template_summary(self, findings: List[Dict], target: str) -> dict:
        """Fallback template when LLM fails."""
        critical = sum(1 for f in findings if f.get("severity") == "critical")
        high = sum(1 for f in findings if f.get("severity") == "high")
        medium = sum(1 for f in findings if f.get("severity") == "medium")
        total = len(findings)

        risk_score = min(10.0, (critical * 10 + high * 7 + medium * 4) / max(total, 1))
        if risk_score >= 8:
            level = "Critical"
        elif risk_score >= 6:
            level = "High"
        elif risk_score >= 3:
            level = "Medium"
        else:
            level = "Low"

        return {
            "executive_summary": f"Security assessment of {target} identified {total} findings "
                                 f"({critical} critical, {high} high, {medium} medium).",
            "technical_summary": f"Found {total} vulnerabilities across multiple categories.",
            "risk_score": round(risk_score, 1),
            "risk_level": level,
            "attack_paths": [],
            "recommendations": [
                "Patch critical and high severity findings immediately.",
                "Implement WAF for web application protection.",
                "Conduct regular security assessments.",
            ],
        }

    def _generate_attack_paths(self, findings: List[Dict]) -> List[str]:
        """Generate attack chain paths from findings."""
        paths = []
        for f in findings[:10]:
            cat = f.get("category", "").lower()
            if "sql" in cat:
                paths.append(f"SQL Injection → Database compromise: {f.get('title', '')}")
            elif "xss" in cat:
                paths.append(f"XSS → Session hijacking: {f.get('title', '')}")
            elif "idor" in cat:
                paths.append(f"IDOR → Unauthorized data access: {f.get('title', '')}")
            elif "ssrf" in cat:
                paths.append(f"SSRF → Internal network scan: {f.get('title', '')}")
            elif "rce" in cat or "command" in cat:
                paths.append(f"RCE → Full server compromise: {f.get('title', '')}")
        return paths[:5]

    def save_report(self, report: AIReport, filename: str = "") -> Path:
        """Save report in multiple formats."""
        if not filename:
            safe_target = report.target.replace("://", "_").replace("/", "_").replace(".", "_")[:50]
            filename = f"itzraven_report_{safe_target}_{datetime.now().strftime('%Y%m%d_%H%M%S')}"

        # Markdown
        md_path = self._report_dir / f"{filename}.md"
        md_path.write_text(report.to_markdown())

        # JSON
        json_path = self._report_dir / f"{filename}.json"
        json_path.write_text(json.dumps({
            "target": report.target,
            "scan_date": report.scan_date,
            "risk_score": report.risk_score,
            "risk_level": report.risk_level,
            "total_findings": report.total_findings,
            "executive_summary": report.executive_summary,
            "findings": [f for sev_list in
                         [report.critical_findings, report.high_findings,
                          report.medium_findings, report.low_findings]
                         for f in sev_list],
            "recommendations": report.recommendations,
            "attack_paths": report.attack_paths,
        }, indent=2))

        logger.info(f"📄 Reports saved to {self._report_dir}/{filename}.*")
        return md_path


_instance_reporter: Optional[AIReportGenerator] = None


def get_ai_reporter() -> AIReportGenerator:
    global _instance_reporter
    if _instance_reporter is None:
        _instance_reporter = AIReportGenerator()
    return _instance_reporter
