"""
Report Drafter - generates platform-compliant bug bounty report markdown
"""

from datetime import datetime
from typing import List, Optional

from itzraven.core.logger import get_logger
from itzraven.core.config import get_config
from itzraven.agents.base_agent import Finding

logger = get_logger()

PLATFORMS = {"hackerone", "bugcrowd", "intigriti"}

REPORT_TEMPLATES = {
    "hackerone": """# Vulnerability Report
**Platform:** HackerOne

## Summary
{title}

## Description
{description}

## Severity
{severity}

## Steps to Reproduce
{reproducibility}

## Proof of Concept
{poc}

## Impact
{impact}

## Remediation
{remediation}

---
*Report generated by Itzraven on {timestamp}*
""",
    "bugcrowd": """# Bugcrowd Vulnerability Submission

## Vulnerability Type
{category}

## Title
{title}

## Description
{description}

## Severity / CVSS
{severity}

## Steps to Reproduce
{reproducibility}

## Proof of Concept (PoC)
{poc}

## Impact
{impact}

## Remediation
{remediation}

## Browser / Environment
N/A

---
*Submitted via Itzraven on {timestamp}*
""",
    "intigriti": """# Intigriti Vulnerability Report

## Vulnerability Title
{title}

## Description / Proof of Concept
{description}

{poc}

## Impact
{impact}

## Recommended Mitigation
{remediation}

## Affected URL(s)
See evidence section

## Evidence
{evidence}

---
*Report drafted by Itzraven on {timestamp}*
""",
}


class ReportDrafter:
    def __init__(self, platform: str = "hackerone"):
        self.platform = platform if platform in PLATFORMS else "hackerone"

    def draft_report(
        self,
        finding: Finding,
        platform: Optional[str] = None,
    ) -> str:
        platform = (platform or self.platform).lower()
        if platform not in PLATFORMS:
            logger.warning(f"Unknown platform '{platform}', falling back to hackerone")
            platform = "hackerone"

        template = REPORT_TEMPLATES[platform]

        reproducibility = ""
        if finding.reproducibility_steps:
            steps = "\n".join(
                f"{i + 1}. {step}"
                for i, step in enumerate(finding.reproducibility_steps)
            )
            reproducibility = steps

        severity_map = {
            "critical": "Critical (P1)",
            "high": "High (P2)",
            "medium": "Medium (P3)",
            "low": "Low (P4)",
            "info": "Informational (P5)",
        }
        severity_label = severity_map.get(finding.severity.lower(), finding.severity)

        report = template.format(
            title=finding.title,
            description=finding.description,
            severity=severity_label,
            category=finding.category,
            reproducibility=reproducibility or "See description",
            poc=finding.proof_of_concept or "N/A",
            impact=self._derive_impact(finding),
            remediation=finding.remediation or "N/A",
            evidence=finding.evidence or "N/A",
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

        logger.info(f"Drafted {platform} report for: {finding.title}")
        return report

    def draft_bugbounty_report(self, findings: List[Finding]) -> str:
        sections: List[str] = [
            "# Bug Bounty Security Report",
            f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')}",
            f"**Total Findings:** {len(findings)}",
            "",
            "---",
            "",
        ]

        for i, finding in enumerate(findings, 1):
            sections.append(f"## Finding {i}: {finding.title}")
            sections.append("")
            sections.append(f"**Severity:** {finding.severity.upper()}")
            sections.append(f"**Category:** {finding.category}")
            sections.append("")
            sections.append("### Description")
            sections.append(finding.description)
            sections.append("")
            if finding.evidence:
                sections.append("### Evidence")
                sections.append(f"```\n{finding.evidence}\n```")
                sections.append("")
            if finding.proof_of_concept:
                sections.append("### Proof of Concept")
                sections.append(f"```\n{finding.proof_of_concept}\n```")
                sections.append("")
            if finding.remediation:
                sections.append("### Remediation")
                sections.append(finding.remediation)
                sections.append("")
            if finding.reproducibility_steps:
                sections.append("### Steps to Reproduce")
                for j, step in enumerate(finding.reproducibility_steps, 1):
                    sections.append(f"{j}. {step}")
                sections.append("")
            sections.append("---")
            sections.append("")

        return "\n".join(sections).strip()

    def draft_multi_platform(self, finding: Finding) -> dict:
        return {
            p: self.draft_report(finding, platform=p)
            for p in PLATFORMS
        }

    @staticmethod
    def _derive_impact(finding: Finding) -> str:
        impact = getattr(finding, "impact", None)
        if impact:
            return impact

        template = (
            f"A {finding.severity} severity {finding.category} vulnerability "
            f"was identified in the target application."
        )
        if finding.severity.lower() in ("critical", "high"):
            template += (
                " This could lead to unauthorized access, data exfiltration, "
                "or complete system compromise."
            )
        elif finding.severity.lower() == "medium":
            template += (
                " This could lead to partial information disclosure or "
                "privilege escalation under specific conditions."
            )
        else:
            template += (
                " While limited in direct impact, this finding provides "
                "useful information for strengthening the security posture."
            )
        return template
